service: emojic

plugins:
    - serverless-python-requirements
    - serverless-prune-plugin
    - serverless-apigw-binary

provider:
    name: aws
    runtime: python3.6
    stage: ${opt:stage, self:custom.defaultStage}
    region: ap-northeast-1
    logRetentionInDays: 14

    apiKeys:
        - emojic_api_key_${self:provider.stage}

    usagePlan:
        quota:
            limit: 5000
            offset: 0
            period: DAY
        throttle:
            burstLimit: 200
            rateLimit: 100

    iamRoleStatements:
        - Effect: Allow
          Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
          Resource:
              - '*'

custom:
    defaultStage: dev

    prune:
        automatic: true
        number: 3

    origin:
        dev: http://localhost:3000
        prod: https://emojic.ch

    needApi:
        dev: false
        prod: true

    apigwBinary:
        types:
            - 'image/jpeg'

package:
    exclude:
        - ./**
    include:
        - detect_face.py
        - haarcascade_frontalface_default.xml
        - emoji/**

functions:
    upload:
        handler: detect_face.lambda_handler
        timeout: 10
        memorySize: 768
        environment:
            EMOJIC_ORIGIN: ${self:custom.origin.${self:provider.stage}}
        events:
            - http:
                  path: upload
                  method: post
                  timeout: 10
                  memorySize: 768
                  private: ${self:custom.needApi.${self:provider.stage}}
                  cors:
                      origin: ${self:custom.origin.${self:provider.stage}}
                      headers:
                          - Content-Type
                          - X-Amz-Date
                          - Authorization
                          - X-Api-Key
                          - X-Amz-Security-Token
                          - X-Amz-User-Agent
